### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Trevo1** [yangppy/VGG_CNN_fruit_recognition#1]
.

**Comment by yangppy** [comment]
我用的百度aistudio平台



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月15日(周一) 下午2:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yangppy/VGG_CNN_fruit_recognition] 请问paddle环境 (Issue #1)




 
你好，请问这个项目的环境是啥呀？ 我装的最新的paddle报了一堆错误...

**Comment by Trevo1** [comment]
本地能运行吗这个仓库😭
